version: 2.1

workflows:
  tooling-vscode-publish:
    jobs:
      - tooling-vscode-publish:
          filters: { branches: { only: [main] } }

# TODO: Move this job to GitHub Actions:
jobs:
  tooling-vscode-publish:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              v1-node-cache-{{ .Branch }}-{{ checksum "tooling/vscode/package-lock.json"
              }}
            - 'v1-node-cache-{{ .Branch }}'
            - v1-node-cache-
      - run:
          working_directory: tooling/vscode
          command: npm install
      - save_cache:
          key: 'v1-node-cache-{{ .Branch }}-{{ checksum "tooling/vscode/package-lock.json" }}'
          paths:
            - node_modules
      - run:
          working_directory: tooling/vscode
          command: npm run-script compile
      - run:
          name: Publish
          working_directory: tooling/vscode
          command: sh -c "npx vsce publish -p $VSCODE_MARKETPLACE_TOKEN 2>&1 | tee /dev/stderr | grep -E 'DONE|Version number cannot be the same'"

executors:
  node:
    description: |
      CircleCI Node Docker image
    docker:
    - image: circleci/node:<<parameters.tag>>
    parameters:
      resource-class:
        default: small
        enum:
        - small
        - medium
        - medium+
        - large
        - xlarge
        type: enum
      tag:
        default: latest
        type: string
    resource_class: <<parameters.resource-class>>
